import type { ReferenceKind } from "../src/schema.js";

export interface CollectionTarget {
  id: string;
  url: string;
  source: string;
  title: string;
  kind: ReferenceKind;
  summary: string;
  components: string[];
  steps: string[];
  avoid: string;
  pageTypes?: string[];
  codeUrl?: string;
  licenseUrl?: string;
  imageSelector?: string;
}

const component = (slug: string, title: string, summary: string, steps: string[], avoid: string): CollectionTarget => ({
  id: `21st-${slug}`, url: `https://21st.dev/@kuratlielia/components/${slug}.md`, source: "21st.dev", title,
  kind: "interaction-pattern", summary, components: [slug], steps, avoid,
  pageTypes: slug === "image-compare" ? ["product-page", "case-study", "portfolio"] : slug === "signature-pad" ? ["form", "onboarding"] : slug === "timeline" ? ["activity-feed", "case-study"] : ["dashboard", "application", "settings"],
});
const shadcn = (slug: string, summary: string, steps: string[], avoid: string, code = false): CollectionTarget => ({
  id: `shadcn-${slug}`, url: `https://ui.shadcn.com/docs/components/${slug}`, source: "shadcn/ui", title: slug.replaceAll("-", " "),
  kind: "code-component", summary, components: [slug], steps, avoid, pageTypes: ["application", "dashboard", "settings"],
  ...(code ? { codeUrl: `https://raw.githubusercontent.com/shadcn-ui/ui/main/apps/v4/registry/new-york-v4/ui/${slug}.tsx`, licenseUrl: "https://raw.githubusercontent.com/shadcn-ui/ui/main/LICENSE.md" } : {}),
});
const radix = (slug: string, summary: string, steps: string[], avoid: string): CollectionTarget => ({
  id: `radix-${slug}`, url: `https://www.radix-ui.com/primitives/docs/components/${slug}`, source: "Radix UI", title: `${slug} behavior`,
  kind: "interaction-pattern", summary, components: [slug], steps, avoid, pageTypes: ["application", "dashboard", "form"],
});
const recent = (slug: string, title: string, summary: string, components: string[], steps: string[], avoid: string): CollectionTarget => ({
  id: `recent-${slug.split("-")[0]}`, url: `https://recent.design/i/${slug}`, source: "recent.design", title,
  kind: "visual-reference", summary, components, steps, avoid, imageSelector: 'meta[property="og:image"]',
  pageTypes: components.includes("portfolio") || components.includes("personal-site") ? ["portfolio"] : components.includes("invite-code") ? ["onboarding", "application"] : ["landing-page", "product-page"],
});

// Bounded source manifest, not a scraped database. Guidance is curator-authored
// and abstracted from the named pattern; collection verifies the source exists.
export const targets: CollectionTarget[] = [
  component("image-compare", "Before/after image comparison", "A draggable divider exposes two aligned images so a viewer can compare a change directly.", ["Use one shared crop and aspect ratio for both images.", "Store the divider as a clamped percentage; update through pointer capture and keyboard arrows.", "Keep a textual explanation of what changed outside the image."], "Unrelated images or a decorative slider without a meaningful comparison."),
  component("date-range-picker", "Date range selection", "A date-range control combines a trigger, calendar selection, and shortcuts for common reporting intervals.", ["Separate temporary calendar selection from the committed filter value.", "Use locale-aware labels, timezone boundaries, and validation for reversed ranges.", "Offer presets only for intervals relevant to the user's task."], "A single date field or a task that never filters by time."),
  component("user-menu", "Account action menu", "An account trigger reveals a compact set of identity, settings, and session actions.", ["Group account identity separately from commands.", "Use a menu primitive with a clear trigger, focus return, and Escape dismissal.", "Place destructive session actions apart from ordinary navigation."], "Hiding a frequently used primary action inside an account menu."),
  component("activity-heatmap", "Time-based activity heatmap", "A compact matrix uses intensity to expose the distribution of activity over a calendar period.", ["Map cells to real dates and give the scale labeled thresholds.", "Provide totals and a non-color representation of each value.", "Allow horizontal scrolling or a shorter range rather than shrinking cells below readable size."], "Sparse data where a short chronological list communicates more clearly."),
  component("brush-chart", "Chart with range brush", "A chart pairs an overview with a selectable interval for closer inspection of time-series data.", ["Keep the full-series overview and detail viewport in one time domain.", "Clamp the selected interval and debounce expensive downstream queries.", "Provide equivalent start/end fields for keyboard and assistive technology users."], "Small datasets that need no zoom or interval selection."),
  component("line-chart", "Line chart for trends", "A line chart emphasizes direction and change in ordered numeric observations.", ["Use a real ordered axis with units, missing-data handling, and a labeled scale.", "Keep a shared tooltip and legend driven by the same data as the plot.", "Add a table or summary for users who cannot interpret the visual chart."], "Unordered categories or invented numbers used as decoration."),
  component("timeline", "Event timeline", "A chronological sequence connects events while preserving the relative importance of their content.", ["Represent events as an ordered list with explicit timestamps.", "Vary event detail according to the available evidence instead of making identical cards.", "Use the connecting line as orientation, not as the only carrier of meaning."], "Numbering ordinary marketing sections that have no chronological relationship."),
  component("usage-meter", "Usage and quota feedback", "A meter explains a consumed amount relative to a real limit and gives context for the remaining capacity.", ["Compute the ratio from actual totals and label both the amount and limit.", "Distinguish normal usage, a warning threshold, and an exceeded state without color alone.", "Keep a useful next action close to the status only when it is relevant."], "Fake performance figures or a row of equal statistic tiles with no user decision attached."),
  component("hover-card", "Supplementary hover preview", "A contextual preview offers optional detail without moving the user away from the current task.", ["Make the underlying link useful even without a preview.", "Delay opening briefly and allow the pointer to travel into the preview.", "Offer a focus or explicit-click path on keyboard and touch devices."], "Essential instructions or controls that are only available on hover."),
  component("signature-pad", "Pointer-driven signature input", "A drawing surface captures a user's signature with clear, undo, and export controls.", ["Record strokes in logical coordinates independent of display pixel density.", "Use pointer events, resize-safe redraw, and an explicit clear action.", "Provide an alternate non-drawing input path where the workflow permits it."], "Using procedural drawing as a substitute for a realistic complex product image."),
  shadcn("tabs", "Tabs switch between related views inside one task while preserving the surrounding context.", ["Keep tab selection explicit and connect each trigger to its panel.", "Use descriptive labels and preserve a panel's local state when useful.", "Avoid hiding a page's primary content behind tabs merely to save vertical space."], "Unrelated routes or a long sequence that users must read in order.", true),
  shadcn("dialog", "A dialog isolates a short, focused decision or edit above the current view.", ["Keep dialog content tied to a single action.", "Define initial focus, Escape behavior, focus return, and an accessible title.", "Keep long workflows on a page rather than nesting multiple dialogs."], "A nonessential interruption or content that belongs directly on the page.", true),
  shadcn("table", "A semantic table keeps repeated records aligned for scanning and comparison.", ["Use real headers, explicit cell meaning, and stable row identifiers.", "Make sorting, filtering, and selection visible only when the dataset needs them.", "Choose horizontal scroll or prioritized columns for narrow screens."], "Wrapping unrelated marketing claims in a table-like three-column rail.", true),
  shadcn("sidebar", "A sidebar maintains orientation in an application with multiple destinations.", ["Group routes according to the user's mental model.", "Clearly show the active route and keep primary navigation stable.", "Collapse to an accessible drawer on small screens without losing destination labels."], "A short landing page with no persistent application navigation."),
  shadcn("combobox", "A searchable selection control helps choose from a larger list of known options.", ["Separate search text, highlighted option, and committed selection.", "Expose loading, no-results, and disabled states.", "Prefer a native select for short lists and ensure keyboard option navigation."], "A handful of options that can be shown directly."),
  shadcn("drawer", "A drawer presents contextual content without replacing the underlying task.", ["Use a clear opening control and dismiss gesture only as a supplement to a button.", "Constrain its height and allow content scrolling without trapping the page accidentally.", "Manage focus and modal semantics consistently with the drawer's behavior."], "A primary workflow that needs a full, stable page."),
  radix("accordion", "Disclosure panels let users inspect optional detail without giving every item equal visual weight.", ["Use heading buttons with expanded state and panel relationships.", "Choose single-open or multi-open behavior according to the content.", "Keep answers immediately meaningful rather than adding decorative numbering."], "Essential information that should be visible by default."),
  radix("select", "An option selector provides a predictable single-choice interaction with keyboard support.", ["Label the field independently from its current value.", "Keep option labels specific and separate unavailable items from empty values.", "Use built-in typeahead and focus behavior rather than recreating a menu with generic divs."], "An action menu or an input that requires free text."),
  radix("popover", "An anchored popover offers a small amount of contextual content beside its trigger.", ["Anchor to the relevant control and handle viewport collisions.", "Keep keyboard dismissal and focus movement clear.", "Use a dialog if the content requires a longer task or multiple steps."], "A large unrelated content panel attached to an arbitrary icon."),
  radix("navigation-menu", "A navigation menu groups related destinations with accessible disclosure behavior.", ["Make top-level labels describe actual destinations or groups.", "Keep link structure usable without hover.", "Use concise groupings based on information architecture, not an equal-card layout quota."], "A small site with only two or three destinations."),
  radix("slider", "A slider changes a bounded numeric value when relative adjustment matters.", ["Expose the current value, limits, units, and step size.", "Support arrows and direct numeric input where precision matters.", "Use a range with two thumbs only when selecting an interval is a real requirement."], "Exact values that are easier and safer to type."),
  { id: "flowbite-datepicker", url: "https://flowbite.com/docs/components/datepicker/", source: "Flowbite", title: "Calendar input states", kind: "interaction-pattern", summary: "A calendar input pairs typed or picked dates with locale, range, and validation states.", components: ["datepicker", "form"], steps: ["Treat the input value as validated date data, not a display string.", "Match calendar constraints to the task's allowed dates.", "Keep errors beside the input and preserve the user's incomplete entry."], avoid: "Adding a custom calendar when a native date field meets the task." },
  { id: "daisyui-chat", url: "https://daisyui.com/components/chat/", source: "daisyUI", title: "Conversation layout", kind: "page-pattern", summary: "A conversation layout organizes messages by sender, time, and reading order rather than interchangeable content cards.", components: ["chat", "message-list"], steps: ["Use an ordered message log with sender labels and timestamps.", "Keep text widths readable and preserve message grouping.", "Announce new messages without forcibly moving the reader's scroll position."], avoid: "Decorative fake chat content unrelated to the product." },
  { id: "headlessui-combobox", url: "https://headlessui.com/react/combobox", source: "Headless UI", title: "Accessible filtered choices", kind: "interaction-pattern", summary: "A headless combobox separates accessible selection behavior from visual presentation.", components: ["combobox", "search"], steps: ["Keep query state separate from the selected object.", "Use the primitive's option and label relationships.", "Apply the project's existing typography, spacing, and focus styles instead of copying a demo theme."], avoid: "Replacing a simple native field for purely visual novelty." },
  recent("ltdfyfe-alim-joldaspayev-portfolio", "Cursor-led portfolio opening", "A portfolio opening uses two labeled cursors and an explicit skip action. Its static poster does not show the rest of the portfolio layout.", ["portfolio", "intro", "cursor"], ["Keep intro content optional and the actual work immediately accessible.", "Treat cursor animation as nonessential presentation with a static reduced-motion alternative.", "Do not infer a complete portfolio layout from an opening animation's first frame."], "Making a visitor wait for an intro before they can access the work."),
  recent("unmc43o-skale-website-footer", "Footer motion and persistent navigation", "A footer preview places a compact navigation strip beneath a field of colored tiles; the gallery poster is only one moment of the source presentation.", ["footer", "navigation", "motion"], ["Keep the actual destinations usable independently of any decorative motion.", "Separate a noninteractive visual layer from readable navigation controls.", "Adapt the information hierarchy, not the source's tile motif, colors, or animation."], "Decorative motion that obscures text or replacing meaningful footer information with animated filler."),
  recent("uugl3yv-sam-cheng-personal-site", "Personal site reference", "A personal-site reference for matching identity, work, and content density to a specific person.", ["personal-site", "typography"], ["Choose a hierarchy around the user's real identity and content.", "Study the relation of text scale, margins, and work evidence.", "Keep source-specific type treatment and composition as evidence, not a template."], "Imitating a portfolio's style when the user's task is an application."),
  recent("p7jwe4i-mobile-wallet-credentials-landing", "Mobile credentials presentation", "A product-presentation reference for making a mobile credential workflow understandable through actual product evidence.", ["product-preview", "mobile", "landing"], ["Use a real product screen or a clearly labeled mockup to explain the core task.", "Keep explanatory copy adjacent to the specific screen state it explains.", "Adapt to the available assets; do not fabricate a detailed product interface."], "Generic device mockups with no relationship to the user's product."),
  recent("ex3s3bx-invite-code-microinteraction", "Invite-code feedback", "An invite-code interaction reference for immediate feedback on a short validation task.", ["invite-code", "feedback", "form"], ["Represent idle, entry, validating, accepted, and rejected states explicitly.", "Keep retry and paste behavior straightforward.", "Adapt the timing and feedback to the task; do not reuse source animation or branding."], "Long or non-interruptible animations delaying a form result."),
];
